import type { Metadata } from "next";
import {Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import {NuqsAdapter} from 'nuqs/adapters/next'
const inter = Inter({
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "AI Agent Platform",
  description: "Generated by create next app",
};

const Layout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <NuqsAdapter>
      <TRPCReactProvider>
        <html lang="en">
          <body className={`${inter.className} antialiased`}>
            <Toaster />
            {children}
          </body>
        </html>
      </TRPCReactProvider>
    </NuqsAdapter>
  );
};
export default Layout;
